### ISSUE TITLE
A couple fixes :)

### ISSUE THREAD

**Issue by caleblawrence** [jacobduncan00/jett#1]
Hello sir, 

I found a couple issues with your app that were causing build issues. The main thing is that Next.js uses file based routing so only put things into `/pages` that you want to actually be a route. You had some react components in a `resuable` folder that it was trying to turn into routes and it couldn't. So I moved those into a `components` folder at the root level of the project. I also moved the contents of `assets` into `public` as that's where they should go I think.

Also I fixed the return syntax in `Active.tsx`. Should be good to go now. Take a look at this commit (I had to fork it and commit on the forked repo):

https://github.com/caleblawrence/jett/commit/f0c57aa450c0d169612cbf3bb6aacd0fc7fd83ce

Regards,
Caleb

**Comment by jacobduncan00** [comment]
Thanks again for your help Caleb, I forgot to close this out a while ago so I'm gonna do it now.
