### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by caleblawrence** [jacobduncan00/jett#3]
Trying using this API url instead of the one you're using: https://api.quotable.io/random (only difference is adding "https" instead of "http").

This is the error being thrown to the console. It doesn't like that you are hitting a HTTP url from a HTTPS website. I tried hitting that same api with HTTPS and it still worked so try switching it and see if that resolves your issue. :)

![image](https://user-images.githubusercontent.com/2174747/102664445-656c9e00-4148-11eb-9486-f8319de24010.png)

**Comment by caleblawrence** [comment]
Make sense why it would work locally and not deployed - the local dev server must not use a real https cert so the browser doesn't enforce those security rules because of that.

**Comment by jacobduncan00** [comment]
Oh ok, this makes sense. Thank you again!
